#!/usr/bin/env ruby
# Usage: pj prepare

# Kill all Solr servers
system("killall -v java; true")

# Run solr for development and test
%w(development test).each do |environment|
  system("bundle exec rake RAILS_ENV=#{environment} sunspot:solr:start")
end

# Pull the origin master
system("git pull origin master")

# Bundle
system("bundle install")

# Migrate the database
system("bundle exec rake db:migrate")

# Run the development server
system("bundle exec rails s")

# Restart Rails application
system("touch tmp/restart.txt")
