#!/usr/bin/env ruby
# Usage: pj prepare
# Summary: Run Solr servers for development and test. Restart the Rails application.

# Kill all solr servers.
system("killall -v java; true")

# Run solr for development and test.
%w(development test).each do |environment|
  puts "Running Solr servers for test and development databases..."
  system("bundle exec rake RAILS_ENV=#{environment} sunspot:solr:start")
end

# TODO: Add more commands depending on the passed attributes,
# like migrating the db, bundle, pulling the current remote master, etc.
# ...

# Restart Rails application.
system("touch tmp/restart.txt")
